# Generated by Django 4.0.1 on 2022-01-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=199, unique=True)),
                ('phone', models.CharField(max_length=255, null=True, unique=True)),
                ('avatar', models.CharField(default='https://testapi.saxonmarket.com/static/images/defaultUser.png', max_length=255)),
                ('pasword', models.CharField(max_length=255)),
                ('verifiedAt', models.DateTimeField(verbose_name='verified at')),
                ('blocked', models.BooleanField(default=False, max_length=1)),
            ],
        ),
    ]
