# Generated by Django 4.0.1 on 2022-01-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pasword',
            new_name='password',
        ),
    ]
