# Generated by Django 4.0.1 on 2022-01-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default='https://testapi.saxonmarket.com/static/images/defaultCategory.png', max_length=255)),
            ],
        ),
    ]
